name: Brewski
url: https://github.com/rorikonn
root: /

menu:
  Home: /
  About: /about
  Archives: /archives
  GitHub: https://github.com/rorikonn
  RSS: /atom.xml

favicon: /favicon.svg
logo: /logo.svg

# Disqus shortname
disqus:

# Analytics
google_analytics:

# Copyright Infomation
copyright:
  since:
  name:
  url:

theme: brewski
theme_config:
  logo:
  google_analytics: 
  copyright:
    since: 2025
    name: Jimmy Zou
    url: https://github.com/rorikonn
  menu:
    Home: /
    About: /about
    GitHub: https://github.com/rorikonn
    RSS: /atom.xml

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/rorikonn/rorikonn.github.io.git
  branch: deploy