logo_title: Jimmyzou's Blog

style: black

favicon: /favicon.ico

menu:
  作品: /project
  域名: /domain
  友联: /links
  关于: /about
  Github: https://github.com/rorikonn

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: false

highlight:
  enable: false